services:
  db:
    image: postgres:17-alpine
    container_name: neo_api_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neo_api_db
    ports:
      - "8000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: neo_api_backend
    restart: always
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/neo_api_db
      - NASA_API_KEY=${NASA_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./frontend:/app/frontend

volumes:
  pgdata:
