CREATE TABLE users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	username VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE neos (
	nasa_id VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	estimated_diameter_min_km DOUBLE PRECISION NOT NULL,
	estimated_diameter_max_km DOUBLE PRECISION NOT NULL,
	is_potentially_hazardous BOOLEAN NOT NULL,
	relative_velocity_km_s DOUBLE PRECISION NOT NULL,
	last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved_neos (
	user_id UUID NOT NULL,
	neo_id VARCHAR(255) NOT NULL,
	saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (user_id, neo_id)
);

CREATE TABLE missions (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL,
	neo_id VARCHAR(255) NOT NULL,
	launch_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	travel_time_days DOUBLE PRECISION NOT NULL,
	status VARCHAR(50) NOT NULL DEFAULT 'IN_TRANSIT'
);
